### ISSUE TITLE
Création de classes

### ISSUE THREAD

**Issue by MaximeVannier27** [MaximeVannier27/ELP#2]
Une classe **Pixel** d'attributs: Red , Green, Blue, Alpha, Coordonnées (x,y), Matrice d'adjacence (rayon de flou*2+1)

Une classe **Image** d'attributs: Matrice RGBA de l'image, taille verticale, taille horizontale, rayon de flou

**Comment by Guewenhtbs** [comment]
Classe faite et fonctionelle
