### ISSUE TITLE
Fonction matrice de voisinage

### ISSUE THREAD

**Issue by MaximeVannier27** [MaximeVannier27/ELP#4]
données en entrée: matrice RGBA

--> configure les matrices de voisinage pour chaque pixel

données en sortie: rien

**Comment by Guewenhtbs** [comment]
pour configurer la matrice on met un 1 s'il existe un voisin à cette position ou un 0 s'il n'existe pas. Ainsi en parcourant cette matrice on pourra connaitre les voisins dont il faudra moyenner les valeurs afin d'obtenir un bon floutage.
